version: '3.8'

services:
  attendance-app:
    image: attendance-app:latest
    ports:
      - "7298:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=attendance.cgs8y3246g1p.us-east-1.rds.amazonaws.com;Port=5432;Database=postgres;Username=postgres;Password=oyC6sTa:6+xTG&t(
      - ASPNETCORE_ENVIRONMENT=Production


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - attendance-app
