version: '3.8'

services:
  # Contêiner da aplicação
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db

  # Contêiner do banco de dados PostgreSQL
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd2023
      POSTGRES_DB: attendance

  # Contêiner do Nginx
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
